package user

import (
	"errors"
	"fmt"

	"golang.org/x/crypto/bcrypt"
)

// service used for interacting with handlers
type Service interface {
	RegisterUser(input RegisterUserInput) (User, error)
	Login(input LoginUserInput) (User, error)
	IsEmailAvailable(input CheckEmailInput) (bool, error)
	SaveAvatar(id int, fileLocation string) (User, error)
	GetUserById(id int) (User, error)
}

type service struct {
	repository Repository
}

// constructor
func CreateService(repository Repository) *service {
	return &service{repository}
}

func (s *service) RegisterUser(input RegisterUserInput) (User, error) {
	// create object user
	user := User{}
	user.Name = input.Name
	user.Email = input.Email
	user.Occupation = input.Occupation

	// create password hash with converted string to byte input password and cost
	password, err := bcrypt.GenerateFromPassword([]byte(input.Password), bcrypt.DefaultCost)

	if err != nil {
		return user, err
	}
	// set user password from generated byte hash password
	user.Password = string(password)

	user.Role = "user"

	newUser, err := s.repository.Save(user)

	if err != nil {
		return newUser, err
	}

	return newUser, nil
}

func (s *service) Login(input LoginUserInput) (User, error) {

	email := input.Email
	password := input.Password

	user, err := s.repository.FindByEmail(email)

	if err != nil {
		return user, err
	}

	if user.Id == 0 {
		return user, errors.New("User not found...")
	}

	err = bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(password))

	if err != nil {
		return user, errors.New("Email or password are incorect...")
	}

	return user, nil
}

func (s *service) IsEmailAvailable(input CheckEmailInput) (bool, error) {

	user, err := s.repository.FindByEmail(input.Email)

	if err != nil {
		return false, err
	}
	// user not found
	if user.Id == 0 {
		return true, nil
	}
	// user not found
	return true, nil
}

func (s *service) SaveAvatar(id int, fileLocation string) (User, error) {
	//find user by id
	user, err := s.repository.FindById(id)

	if err != nil {
		return user, err
	}
	// assign user avatar file location with current location
	user.AvatarFileName = fileLocation
	// update the user
	updatedUser, err := s.repository.Update(user)

	if err != nil {
		return updatedUser, err
	}

	return updatedUser, nil

}

func (s *service) GetUserById(id int) (User, error) {
	user, err := s.repository.FindById(id)

	if err != nil {
		return user, errors.New(fmt.Sprintf("No user found with id: %d", id))
	}

	return user, nil
}
